index.js

I wasn't able to get tsc-watch to run on my mac until I added the shebang and changed line endings to unix.

Add shebang

---

lib/tsc-watch.js

This is a very simple fix for #15. It just outputs the text without adding any special color in the default case.

Fix default color

---

lib/tsc-watch.js
package.json

Hi team,
When using the tsc-watch client, I noticed that `client.kill()` doesn't actually kill tsc-watch or `tsc`. When my parent process exits, `pstree` shows them hanging around as orphans until I directly kill them. ([client.js](https://github.com/gilamran/tsc-watch/blob/master/lib/client.js#L12) uses `childProcess.kill()`, which sends a `SIGTERM`).
You can reproduce this problem on any project that uses the most recent version of tsc-watch:
```bash
$ tsc-watch --preserveWatchOutput &
[2] 66473
...
$ kill -s SIGTERM 66473
$ pstree | grep -A1 66473
```
It looks like this problem was partially introduced by #23. Prior to that change, SIGTERM would kill the `tsc-watch` process, but not the `tsc` process. With that change, neither process would exit from a SIGTERM. This was due to a …

Fix `client.kill()`, and tsc-watch SIGTERM handling

---

lib/args-manager.js
package-lock.json
test/args-manager.it.js

makes sure if `-w` or `--watch` options was not added by the user the forced watch will not add it at the begging of the arguments (breaking some weird desire for tsc to have the `-b` or `--build` option as first argument)

Fixes tsc desire for `--build` or `b` to be first option

---

README.md
lib/client.js
test/client.it.js

Fixes https://github.com/gilamran/tsc-watch/issues/51
I have only fixed the existing tests, because basically running two tsc-watch side-by-side sounds like testing how `fork` works in Node.js, but please let me know if you think otherwise 🙃 
ps: Running tests was a bit cumbersome because I had to run `npm add typescript`. Not sure it has to be addressed, just sharing my finding.
ps2: Would be cool to add Travis CI or Appveyor to run tests 😄

Export TscWatchClient and update tests

---

lib/killer.js
lib/tsc-watch.js

Added graceful shutdown.
From now on, we're waiting for all the child processes to complete their shutdown before `tsc-watch` exits

Graceful shutdown

---

lib/killer.js

Add /F option for forcefully terminate windows process.
[Nodemon](https://github.com/remy/nodemon/blob/20ccb623c4/lib/monitor/run.js#L334) already using this.

Force kill child process, when windows.

---

lib/stdout-manipulator.js
lib/tsc-watch.js

This change supports older version of the TypeScript compiler as they have a different output when in watch mode. In version 2.7.2, the compiler always writes `Compilation complete. Watching for file changes.` even though there are errors. So one needs to keep track of the errors as they occur.

Add support for TypeScript 2.7.2 when parsing the output from tsc

---

lib/killer.js
package-lock.json
package.json
test/client.it.js
test/runner.it.js

I noticed that my package.json scripts weren't being killed after the update to version 2.4.6. If I read the documentation correctly (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/kill.html) the actual kill command should be `kill -15`.
This PR contains that update as well as a unit test to hopefully check the positive and negative case.

Change kill signal and add unit test

---

lib/tsc-watch.js

**What's the problem this PR addresses?**
`tsc-watch` tries to spawn the TypeScript compiler by passing the path to the javascript file directly to `cross-spawn`. This doesn't work under Yarn PnP where the file is within a zip archive, so we need to explicitly tell `cross-spawn` to spawn it using node.
Fixes https://github.com/gilamran/tsc-watch/issues/79
**How did you fix it?**
Spawn the typescript compiler using node

fix: spawn compiler using node

---

package-lock.json
package.json

BREAKING CHANGE: these deps now require node 8 or higher
Node 8 went out of support in Dec 2019, but is still popular enough that most
libraries kinda support it (including me).
Travis is only set to test 8+, so I guess that's the policy here too.
* https://github.com/moxystudio/node-cross-spawn/blob/master/CHANGELOG.md
* https://github.com/chalk/strip-ansi/releases
* https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md
(My goal is to remove `lru-cache` from our dep tree, which is dropped by `cross-spawn@^6`.)

fix: upgrade cross-spawn and strip-ansi (node 8+)

---

lib/args-manager.js

**What's the problem this PR addresses?**
`tsc-watch` tries to resolve the compiler provided in the `--compiler` flag from itself instead of the context that provides it.
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
Fixes https://github.com/gilamran/tsc-watch/issues/110
**How did you fix it?**
Resolve the `--compiler` flag from the cwd

fix: resolve compiler flag from cwd

---

.gitignore
CHANGELOG.md
README.md
lib/args-manager.js
lib/client.js
lib/stdout-manipulator.js
lib/tsc-watch.js
package.json
test/args-manager.it.js
test/client.it.js
test/runner.it.js
test/tsc-watch.it.js
tsc-watch-client-example.js

- Implement the idea in https://github.com/gilamran/tsc-watch/issues/120
- Enable all existing unit tests (it seems like they were accidentally disabled by committing describe.only), fix broken ones
- Add new unit tests for --onCompilationStarted
- Make CHANGELOG.md to look stylistically consistently
- In the code, rename newCompilation* variables to compilationStarted* to make naming more consistent with compilationComplete* variable
Also, additionally tested this PR manually with:
```bash
node ./index.js test/fixtures/failing.ts --outDir ./dist --onCompilationStarted "echo STARTED" --onSuccess "echo SUCCESS"
node ./tsc-watch-client-example.js
```
P.S.
The usecase explanation for this new --onCompilationStarted option on my end is here: https://github.com/webpack/webpack/issues/13978
In …

Add onCompilationStarted option, enable  and fix all unit tests

---

README.md
lib/args-manager.js
lib/tsc-watch.js
test/args-manager.it.js

This adds another option: `--silent`. This option enables you not to show any logs on the console.
I'm using this module as a library on [Glee](https://www.github.com/asyncapi/glee) and the compilation is a process that should happen behind the scenes, without the user noticing.
I thought this would be useful for others too.
Cheers, and thanks for the great work! 🙌

feat: add --silent option

---

README.md
lib/args-manager.js
lib/tsc-watch.js
test/args-manager.it.js

Issue: https://github.com/gilamran/tsc-watch/issues/137
Read issue for more, in short:
- Add new param `--maxNodeMem 1234`
- If this param is set, call  `node` with additional mem tweak `--max_old_space_size=1234`

Add `--maxNodeMem` param to tweak node tsc allocated memory

---

CHANGELOG.md
README.md
lib/client.js
lib/stdout-manipulator.js
lib/tsc-watch.js
test/client.it.js
test/stdout-manipulator.it.js

Issue: https://github.com/gilamran/tsc-watch/issues/138 read for more
What does this PR:
- Handle `--listEmittedFiles` param and call `tsc` accordingly
- Update `tsc-watch` to send `file_emitted:<filepath>`
- Make client emit `file_emitted:` with the `<filePath>`
I've put grey color because TSFILE are not very important see
(Tests are passing)

Support  for `--listEmittedFiles` + new message `file_emitted`

---

src/client/client.ts
src/lib/tsc-watch.ts
src/test/client.test.ts

Fixes https://github.com/gilamran/tsc-watch/issues/136 (exhaustive issue)
Improved client error handling:
- when `tsc-watch.js` crashes with a signal (`SIGKILL`, `SIGABRT`), it will kill it with the **same signal**
- `tsc` stderr was lost for parent processes - it's now piped to the tsc-watch stderr
Purpose of this PR is to not make devs spend time finding out why tsc crash behing TscWatchClient / tsc-watch.
Probably everybody expect this behavior (do they? I hope so), in any case we are making it part of v6 major

feat(136): improve error handling on tsc fatal signals

---

README.md
src/lib/args-manager.ts
src/lib/stdout-manipulator.ts
src/lib/tsc-watch.ts
src/test/args-manager.test.ts
src/test/stdout-manipulator.test.ts

In #140 I've added support to new event `.on(`file_emitted`)`. This feature works as long `--listEmittedFiles` param is set.
Problem: `--listEmittedFiles`is noisy and print a bunch of `TSFILE: /path/to/emitted/files.js`
@gilamran have suggested a new param `--signalEmittedFiles` which would make the event work, but silently.
- parse `--signalEmittedFiles` (boolean)
- make it call tsc with `--listEmittedFiles`
- make it hide ines starting with `TSFILE:`

feat(140): add `--signalEmittedFiles` and trigger `file_emitted` silently

---

client.d.ts
client.js
package.json
src/lib/stdout-manipulator.ts
src/lib/tsc-watch.ts

Follow v6 pre release tries: https://github.com/gilamran/tsc-watch/discussions/145
Summary:
- regression: disable back TSFILE (emitted files log) useless styling
- major: fix `--listEmittedFiles` param in node tsc syscall
- improvement: enables to import `/client` instead of `dist/client`

fix: v6 fixes

---

README.md
tsc-watch-client-example.js

Fixes #156
`export default` is very discouraged in ES6 world:
- https://rajeshnaroth.medium.com/avoid-es6-default-exports-a24142978a7a
- https://blog.piotrnalepa.pl/2020/06/26/default-exports-vs-named-exports/
- https://www.reddit.com/r/javascript/comments/9amkc6/export_default_considered_harmful/
In fact while trying to do it I've faced typical problems because there is some ugly trick to be done for `export default` to not export an Object with a `default` field into it and so on. So in this PR I just fix the documentation in README and in the example script. IMHO this is better since:
- If we change the way `TscWatchClient` must be imported it would mean a compability breaking change.
- `tsc-watch` changed this in 6.0.0 version, which is a mayor update so it's ok to break backwards …

Fix documentation regarding how to import/require TscWatchClient from 'tsc-watch/client'

---

src/lib/args-manager.ts
src/lib/tsc-watch.ts
src/test/args-manager.test.ts

Problem
---
When we use `--signalEmittedFiles` it will insert `--listEmittedFiles` and then `tsc` will complain
> Option '--build' must be the first command line argument.
Solution
---
Extract `-b`/`--build` and move it before `--listEmittedFiles`.

fix: error TS6369: Option '--build' must be the first command line argument.

---

package.json

- needs `npm run build` since the latest npm code doesn't have the latest changes: https://www.npmjs.com/package/tsc-watch?activeTab=code
- `prepublish` got deprecated in npm 5 (2017) for `prepublishOnly`: https://docs.npmjs.com/cli/v6/using-npm/scripts

build: run build in prepublishOnly

---

src/lib/args-manager.ts
src/test/args-manager.test.ts

This PR addresses an off-by-one issue in `isCommandExist(args, command)` within args-manager.ts (as noted in [issue #154](https://github.com/gilamran/tsc-watch/issues/154#issuecomment-2888568618)) that causes tsc-watch not to detect when `--watch` is provided as the very first parameter on the tsc-watch command line.
Assertions within the associated unit test have also been "tightened" to properly detect this (now resolved) error.
Note that with this change the `--no-watch` capability requested in issue #154 is now reliably available by passing `--watch false` on the `tsc-watch` command line. (To be clear, as noted in the issue discussion thread, this capability was already _generally_ available, but due to the bug addressed by this PR it would not work when `--watch` was the very first …

bugfix/issue-154: detect when --watch or -w is already provided in tsc-watch command line, even as the first parameter
